reCAPTCHA: fix TypeError
TypeError: json_decode() expects parameter 1 to be string, object given in /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/Auth/Recaptcha/RecaptchaVerify.php:49
Stack trace:
#0 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/Auth/Recaptcha/RecaptchaVerify.php(49): json_decode()
#1 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Controllers/Auth.php(468): CDCMastery\Models\Auth\Recaptcha\RecaptchaVerify->verify()
#2 [internal function]: CDCMastery\Controllers\Auth->do_registration()
#3 /home/vhosts/cdcmastery.com/app-deploy/vendor/php-di/invoker/src/Invoker.php(83): call_user_func_array()
#4 /home/vhosts/cdcmastery.com/app-deploy/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call()
#5 /home/vhosts/cdcmastery.com/app-deploy/public/index.php(125): DI\Container->call()
#6 {main}