offline tests: fix issue where deleted questions cause a TypeError
TypeError: Argument 1 passed to CDCMastery\Models\CdcData\AnswerCollection::CDCMastery\Models\CdcData\{closure}() must be an instance of CDCMastery\Models\CdcData\Question, int given in /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/CdcData/AnswerCollection.php:301
Stack trace:
#0 [internal function]: CDCMastery\Models\CdcData\AnswerCollection::CDCMastery\Models\CdcData\{closure}()
#1 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/CdcData/AnswerCollection.php(301): array_map()
#2 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/CdcData/QuestionAnswersCollection.php(44): CDCMastery\Models\CdcData\AnswerCollection->fetchByQuestions()
#3 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Models/Tests/Offline/OfflineTestCollection.php(460): CDCMastery\Models\CdcData\QuestionAnswersCollection->fetch()
#4 /home/vhosts/cdcmastery.com/app-deploy/src/CDCMastery/Controllers/Overviews/TrainingOverview.php(529): CDCMastery\Models\Tests\Offline\OfflineTestCollection->fetchAllByUser()
#5 [internal function]: CDCMastery\Controllers\Overviews\TrainingOverview->show_offline_tests()
#6 /home/vhosts/cdcmastery.com/app-deploy/vendor/php-di/invoker/src/Invoker.php(83): call_user_func_array()
#7 /home/vhosts/cdcmastery.com/app-deploy/vendor/php-di/php-di/src/Container.php(276): Invoker\Invoker->call()
#8 /home/vhosts/cdcmastery.com/app-deploy/public/index.php(123): DI\Container->call()
#9 {main}